server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: weico
  redis:
    host: 47.108.140.33 # Redis服务器地址
    database: 6 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Ectrip2020 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

#mybatis:
#  mapper-locations:
#    - classpath:mapper/*.xml
#    - classpath*:com/**/mapper/*.xml
logging:
  level:
    com:
      yangya: debug
    org:
      mybatis: debug
#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
#      table-prefix: t_
      table-underline: true
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: com.yangya.model

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
